### PR TITLE
feat: add support for configuring CDN

### LINKED ISSUE #362: Allow cdn in AnalyticsSettings
Hello 👋 

If I understand correctly the current way to set the cdn is this 

```ts
window.analytics._cdn = <cdn>
```

Because this variable can then be reused in the plugins 

We try to avoid touching the window object as much as possible 
Would it be possible to pass the cdn in the AnalyticsSettings which is then passed down to the plugins ? 

```ts
AnalyticsBrowser.load({ writeKey, cdn })
```

```ts
export function loadLegacySettings(writeKey: string, cdn: string): Promise<LegacySettings> {
  return fetch(`${cdn}/v1/projects/${writeKey}/settings`)
    .then((res) => ({ ...res.json(), cdn }))
    .catch((err) => {
      console.warn('Failed to load settings', err)
      throw err
    })
}
```

Thanks :)

### PR DESCRIPTION
**Pull request by yordis**
fixes #362

### CODE REVIEW

**Comment by pooyaj** [comment]
awesome! thanks @yordis 🎉 There are few places that we need to propagate the CDN address to as well. For example, when loading destinations/remote-plugins/etc. ... searching the codebase for `cdn = window.analytics?._cdn ?? getCDN()` will give you pointers to that. Can we update those as well? Happy to tackle internally as well if it looks tedious to support.

**Comment by yordis** [comment]
@pooyaj happy to fix everything, I wasn't aware of them. Let me dig into it.

**Comment by silesky** [comment]
@yordis, thank you for your contribution, this is useful! I'm continuing your work in this PR https://github.com/segmentio/analytics-next/pull/414, and am working to bring it across the finish line.

**Comment by yordis** [comment]
@silesky please feel free to take over if you finish first, I don't mind at all, I was about to work on this over the weekend. So if you have bandwidth before, keep going.

**Comment by silesky** [comment]
Continued in https://github.com/segmentio/analytics-next/pull/414

**Pull request closed without merging**
